import { MarquePorteur } from "./marque-porteur"

export interface OptionsPorteur {
    id?: number,
    marquePorteur?: MarquePorteur,
    modelePorteur?: string,
    cylindree?: number,
    motorisation?: string,
    puissanceDin?: number,
    puissanceFiscale?: number,
    abs?: boolean,
    airbag?: boolean,
    autoradio?: boolean,
    ClimaPorteur?: boolean,
    retroviseurElect?: boolean,
    siegeCabConfort?: boolean,
    vitresElectr?: boolean,
    verrouillage?: boolean,
    antiBrouillard?: boolean,
    cameraRecoule?: boolean,
    esp?: boolean,
    retroviseurElectr?: boolean,
    stopStart?: boolean,
    euro6?: boolean,
    feuxLed?: boolean,
    rideauIso?: boolean,
    gps?: boolean,
    asr?: boolean,
    antiDemarrage?: boolean,
}
